CREATE TABLE if not exists t_orders (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	order_number varchar(255) DEFAULT NULL,
    sku_code  varchar(255) NULL,
    price decimal(19, 2) NULL,
    quantity int8,
	PRIMARY KEY (id)
);