server.port: 8080
server.error.include-message: always

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: PRODUCT-SERVICE
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/api/product
          - id: ORDER-SERVICE
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/order
          - id: INVENTORY-SERVICE
            uri: lb://INVENTORY-SERVICE
            predicates:
              - Path=/api/inventory

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring.config.activate.on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka