spring.application.name: order-service

server.port: 8082
server.error.include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    com.academy.microservices.order: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka