spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://configuser:password123@localhost:8989

#Resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5

  #Resilience4J Timeout Properties
  timelimiter:
    instances:
      inventory:
        timeoutDuration: 3s

  #Resilience4J Retry Properties
  retry:
    instances:
      inventory:
        maxAttempts: 3
        waitDuration: 5s

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---
spring.config.activate.on-profile: docker

server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka