server.port: 8081
server.error.include-message: always

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      username: ${SPRING_DATA_MONGODB_USERNAME:root}
      password: ${SPRING_DATA_MONGODB_PASSWORD:password}
      authentication-database: ${SPRING_DATA_MONGODB_AUTH_DB:admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}

logging:
  level:
    root: INFO
    com.academy.microservices.product: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

# zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---
spring.config.activate.on-profile: docker

server.port: 8080

spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongo}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      username: ${SPRING_DATA_MONGODB_USERNAME:root}
      password: ${SPRING_DATA_MONGODB_PASSWORD:password}
      authentication-database: ${SPRING_DATA_MONGODB_AUTH_DB:admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://eureka-server:8761/eureka}