spring.application.name: inventory-service

server.port: 8083
server.error.include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_service
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.academy.microservices.inventory: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory_service