spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:http://configuser:password123@localhost:8989

---
spring.config.activate.on-profile: docker

server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory_service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka