spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:http://configuser:password123@localhost:8989

# zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---
spring.config.activate.on-profile: docker

server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory_service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka